version: '3'

services:

  alertmanager:
      container_name: alertmanager
      image: prom/alertmanager:v0.5.0
      restart: always
      ports:
          - "9093:9093"
      volumes:
          - ./alertmanagerdata:/etc/alertmanager:rw

  blackbox-exporter:
      container_name: blackbox-exporter
      restart: always
      image: prom/blackbox-exporter:v.1.0.0
      ports:
          - "9115:9115"
      volumes:
          - ./blackboxdata/config:/config
      command: -config.file=/config/blackbox.yml

  trx-exporter:
      container_name: trx-exporter
      restart: always
      image: trx-exporter
      links:
       - prometheus
      ports:
          - "9981:9981"
      volumes:
          - ./trxexporterdata/script:/root/exporter:rw

  trx-remittance:
      container_name: trxremit
      restart: always
      image: bagusajah/rasuna:trxremit
      links:
       - prometheus
      ports:
          - "9982:9982"
      volumes:
          - ./trxremitdata/script:/root/exporter:rw

  prometheus:
      container_name: prometheus
      image: prom/prometheus:v1.5.2
      links:
       - alertmanager
       - blackbox-exporter
      command: -config.file=/etc/prometheus/prometheus.yml -alertmanager.url=http://alertmanager:9093
      restart: always
      ports:
          - "9090:9090"
      volumes:
          - ./prometheusdata:/etc/prometheus:rw
          - ./prometheusdb2:/prometheus/data:rw

