version: "2"

services:
  grafana:
    container_name: grafana
    restart: always
    image: grafana/grafana:4.1.1
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=jdbranham-diagram-panel,grafana-piechart-panel
